# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='status',
            field=models.CharField(default='shelf', max_length=80),
        ),
    ]
