# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='return_date',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 9, 49, 2, 658120), null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='return_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 9, 49, 2, 658150), null=True),
        ),
    ]
