# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('copy_no', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaialability', models.BooleanField(default=False)),
                ('student_rollno', models.CharField(blank=True, max_length=20)),
                ('book_id', models.PositiveIntegerField()),
                ('issued', models.BooleanField(default=False)),
                ('issue_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('renewed_date', models.DateField()),
            ],
        ),
    ]
