# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170830_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copy_no',
        ),
    ]
